# -*- coding: utf-8 -*-

'''
Copyright (C) 2014 ITI GmbH
All rights reserved.

This file is part of PySimulator.

PySimulator is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PySimulator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with PySimulator. If not, see www.gnu.org/licenses.
'''

unitSI = dict()
unitSI['AbsTemp'] = u'K'
unitSI['Accel'] = u'm/s²'
unitSI['Acceleration'] = u'm/s²'
unitSI['AcousticAdmittance'] = u'(m³/s)/Pa'
unitSI['AcousticCompliance'] = u'm³/Pa'
unitSI['AcousticImpedance'] = u'Pa/(m³/s)'
unitSI['AcousticMass'] = u'kg/m^4'
unitSI['AmplCurrentContr'] = u'A/(rad/s)'
unitSI['Angle'] = u'rad'
unitSI['AngularAcceleration'] = u'rad/s²'
unitSI['AngularMomentum'] = u'Nms'
unitSI['AngularVelocity'] = u'rad/s'
unitSI['Area'] = u'm²'
unitSI['AreaPDisplChange'] = u'm²/m'
unitSI['BEConst'] = u'Vs/rad'
unitSI['Beta'] = u'1/Pa'
unitSI['Beta_h'] = u'm³/J'
unitSI['Beta_p'] = u'm³/(kg·Pa)'
unitSI['CAccFeedbackGain'] = u'A/(m/s²)'
unitSI['CPosFeedbackGain'] = u'A/m'
unitSI['CPressFeedbackGain'] = u'A/Pa'
unitSI['CROCPressFeedbackGain'] = u'A/(Pa/s)'
unitSI['CRotAccFeedbackGain'] = u'A/(rad/s²)'
unitSI['CRotAngleFeedbackGain'] = u'A/rad'
unitSI['CRotVeloFeedbackGain'] = u'A/(rad/s)'
unitSI['CVeloFeedbackGain'] = u'A/(m/s)'
unitSI['Capacitance'] = u'F'
unitSI['CapacityFactor'] = u'(rad/s)/Nm^0.5'
unitSI['Conductance'] = u'1/Ohm'
unitSI['Conductivity'] = u'S/m'
unitSI['ConstC'] = u's/m'
unitSI['ConvCoeff'] = u'W/(m²·K)'
unitSI['Current'] = u'A'
unitSI['CurvatureVel'] = u'1/m/s'
unitSI['Damping'] = u'1/s'
unitSI['DampingperArea'] = u'Ns/m/m²'
unitSI['DataRate'] = u'bit/s'
unitSI['DataWith'] = u'bit'
unitSI['Density'] = u'kg/m³'
unitSI['DensityChangeRate'] = u'kg/(m³·s)'
unitSI['Displace'] = u'm'
unitSI['DynVisc'] = u'Pa·s'
unitSI['EFieldStrength'] = u'V/m'
unitSI['EModul'] = u'Pa'
unitSI['Echarge'] = u'C'
unitSI['ElastCoeff'] = u'm²/N'
unitSI['ElectricCurrent'] = u'A'
unitSI['ElectricPotential'] = u'V'
unitSI['Energy'] = u'J'
unitSI['EnthalpyFlow'] = u'J/s'
unitSI['EquBulkMod'] = u'Pa'
unitSI['Flow'] = u'm³/s'
unitSI['FlowDensity'] = u'kg/m²/s'
unitSI['FlowPDisplChange'] = u'(m³/s)/m'
unitSI['FlowPRelChanging'] = u'(m³/s)/-'
unitSI['Force'] = u'N'
unitSI['ForceConst'] = u'N/A'
unitSI['ForcePPressChange'] = u'N/Pa'
unitSI['Frequency'] = u'Hz'
unitSI['FuelConsumption'] = u'kg/Ws'
unitSI['Gamma'] = u'1/K'
unitSI['GasConst'] = u'J/(kg·K)'
unitSI['Gradient'] = u'1/s'
unitSI['GrashofNum'] = u'1/K'
unitSI['Heat'] = u'J'
unitSI['HeatCapacity'] = u'J/K'
unitSI['HeatCapacityDeriv'] = u'W/K'
unitSI['HeatCond'] = u'W/K'
unitSI['HeatConduct'] = u'W/K'
unitSI['HeatFlow'] = u'W'
unitSI['HeatFlowPerKevin4'] = u'W/K^4'
unitSI['HeatFlowSurf'] = u'W/m²'
unitSI['HeatRate'] = u'J/Ws'
unitSI['HeatResist'] = u'K/W'
unitSI['HeatTransmCoeff'] = u'W/(m²·K)'
unitSI['HydrCapacity'] = u'm³/Pa'
unitSI['HydrConduct'] = u'(m³/s)/Pa'
unitSI['HydrInduct'] = u'kg/(m^4)'
unitSI['Inductance'] = u'H'
unitSI['IntegrAmplGain'] = u'(A/s)/V'
unitSI['InverseVoltage'] = u'1/V'
unitSI['KinVisc'] = u'm²/s'
unitSI['KvFactor'] = u'm³/s'
unitSI['Length'] = u'm'
unitSI['LinDamping'] = u'Ns/m'
unitSI['LinFlexibility'] = u'm/N'
unitSI['LinRotRatio'] = u'm/rad'
unitSI['LinStiffness'] = u'N/m'
unitSI['LineCapacitance'] = u'F/m'
unitSI['LineConductance'] = u'1/(Ohm·m)'
unitSI['LineInductance'] = u'H/m'
unitSI['LineResistance'] = u'Ohm/m'
unitSI['LogGain'] = u'dB20'
unitSI['MagConductance'] = u'H'
unitSI['MagField'] = u'A/m'
unitSI['MagFieldConstant'] = u'H/m'
unitSI['MagFlux'] = u'Wb'
unitSI['MagFluxDensity'] = u'T'
unitSI['MagFluxDer'] = u'Wb/s'
unitSI['MagPot'] = u'A'
unitSI['MagPotDer'] = u'A/s'
unitSI['MagResistance'] = u'1/H'
unitSI['Mass'] = u'kg'
unitSI['MassFlow'] = u'kg/s'
unitSI['MassFraction'] = u'-'
unitSI['MassPerLength'] = u'kg/m'
unitSI['MolarMass'] = u'kg/mol'
unitSI['MomOfArea'] = u'm^4'
unitSI['MomentOfInertia'] = u'kgm²'
unitSI['Momentum'] = u'Ns'
unitSI['Number'] = u'piece(s)'
unitSI['OpenLoopGain'] = u'1/s'
unitSI['ParticleDensity'] = u'1/m³'
unitSI['PneuCapacity'] = u'm·s²'
unitSI['PneuInductance'] = u'1/m'
unitSI['PneuResist'] = u'Pa/(kg/s)'
unitSI['Power'] = u'W'
unitSI['PowerOfSound'] = u'W'
unitSI['PressChangePFlowRateChange'] = u'Pa/(m³/s)'
unitSI['Pressure'] = u'Pa'
unitSI['PropAmplGain'] = u'A/V'
unitSI['RateOfTempRise'] = u'K/s'
unitSI['RatePressRise'] = u'Pa/s'
unitSI['Real'] = u'-'
unitSI['ReciArea'] = u'1/m²'
unitSI['ReciDisplace'] = u'1/m'
unitSI['ReciHeatTransmCoeff'] = u'(m²·K)/W'
unitSI['ReciIntegrAmplGain'] = u'(V/s)/A'
unitSI['ReciPropAmplGain'] = u'V/A'
unitSI['ReciRotVelocity'] = u's/rad'
unitSI['ReciTemp'] = u'1/K'
unitSI['ReciTemp2'] = u'1/°C²'
unitSI['ReciVelocity'] = u's/m'
unitSI['RelMagnitude'] = u'-'
unitSI['Resistance'] = u'Ohm'
unitSI['Resistivity'] = u'Ohm·m'
unitSI['RotAccel'] = u'rad/s²'
unitSI['RotDamping'] = u'Nms/rad'
unitSI['RotFlexibility'] = u'rad/Nm'
unitSI['RotLinRatio'] = u'rad/m'
unitSI['RotStiffness'] = u'Nm/rad'
unitSI['RotVelocity'] = u'rad/s'
unitSI['Roughness'] = u'm'
unitSI['SCriticalConduct'] = u'm³/(Pa·s)'
unitSI['SpecBendDamp'] = u'Nm²s'
unitSI['SpecBendStiff'] = u'Nm²'
unitSI['SpecDamping'] = u'Ns/m²'
unitSI['SpecEnergy'] = u'J/kg'
unitSI['SpecEnthalpy'] = u'J/kg'
unitSI['SpecHeat'] = u'J/(kg·K)'
unitSI['SpecHeatCapacity'] = u'J/(kg·K)'
unitSI['SpecHeatCond'] = u'W/(m·K)'
unitSI['SpecStiffness'] = u'N/m/m'
unitSI['SpecStretchDamp'] = u'Ns'
unitSI['SpecVolume'] = u'm³/kg'
unitSI['SpecWeight'] = u'N/m³'
unitSI['Speed'] = u'rad/s'
unitSI['StiffnessperArea'] = u'N/m/m²'
unitSI['SurfTens'] = u'N/m'
unitSI['Temp'] = u'K'
unitSI['TempDiff'] = u'K'
unitSI['TempGrad'] = u'K/s'
unitSI['Tension'] = u'Pa'
unitSI['ThermConductivity'] = u'W/(m·K)'
unitSI['ThermodynamicTemperature'] = u'K'
unitSI['Time'] = u's'
unitSI['Torque'] = u'Nm'
unitSI['TorqueConst'] = u'Nm/A'
unitSI['TorquePPressChange'] = u'Nm/Pa'
unitSI['TransCondPar'] = u'A/V²'
unitSI['Unbalance'] = u'kgm'
unitSI['Unitless'] = u'-'
unitSI['VAccFeedbackGain'] = u'V/(m/s²)'
unitSI['VPosFeedbackGain'] = u'V/m'
unitSI['VPressFeedbackGain'] = u'V/Pa'
unitSI['VROCPressFeedbackGain'] = u'V/(Pa/s)'
unitSI['VRotAccFeedbackGain'] = u'V/(rad/s²)'
unitSI['VRotAngleFeedbackGain'] = u'V/rad'
unitSI['VRotVeloFeedbackGain'] = u'V/(rad/s)'
unitSI['VVeloFeedbackGain'] = u'V/(m/s)'
unitSI['VeloSound'] = u'm/s'
unitSI['Velocity'] = u'm/s'
unitSI['VolExpCoeff'] = u'1/K'
unitSI['VolIncPPressChange'] = u'm³/m/Pa'
unitSI['VolPLength'] = u'm³/m'
unitSI['VolSpecEnergy'] = u'J/m³'
unitSI['Voltage'] = u'V'
unitSI['Volume'] = u'm³'
unitSI['VolumeChangePerAngleChange'] = u'm³/rad'
unitSI['VolumeFlow'] = u'm³/s'
unitSI['VolumeFraction'] = u'-'
unitSI['dmp_dp'] = u'(kg/s)/Pa'
